//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\danie\Documents\Projecten\FlyLang\FlyLang.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FlyLang.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FlyLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IFlyLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] FlyLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] FlyLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] FlyLangParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] FlyLangParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUse([NotNull] FlyLangParser.UseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] FlyLangParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.classDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDef([NotNull] FlyLangParser.ClassDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] FlyLangParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.elifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElifStmt([NotNull] FlyLangParser.ElifStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.elseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStmt([NotNull] FlyLangParser.ElseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStmt([NotNull] FlyLangParser.WhileStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStmt([NotNull] FlyLangParser.ForStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] FlyLangParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNames([NotNull] FlyLangParser.NamesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] FlyLangParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] FlyLangParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.newClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewClass([NotNull] FlyLangParser.NewClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.varCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarCall([NotNull] FlyLangParser.VarCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] FlyLangParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] FlyLangParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.intLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLit([NotNull] FlyLangParser.IntLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.floatLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLit([NotNull] FlyLangParser.FloatLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] FlyLangParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] FlyLangParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.dictionary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionary([NotNull] FlyLangParser.DictionaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.keyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyItem([NotNull] FlyLangParser.KeyItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FlyLangParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] FlyLangParser.IdContext context);
}
} // namespace FlyLang.Parser
